language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack-dev libnetcdf-dev
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
