language: python
python:
  - "2.7"
before_install:
  - apt-get update -qq
  - apt-get install -qq liblapack-dev 
  - apt-get install -qq libhdf5-serial-dev hdf5-tools 
  - apt-get install libnetcdf-dev
  - apt-get install libzmq3-dev
  - apt-get install python-numpy 
  - apt-get install python-scipy 
  - apt-get install python-matplotlib 
#  - pip install numpy
#  - pip install scipy
  - pip install -Iv https://bitbucket.org/jamesrhester/pycifrw/downloads/PyCifRW-3.6.1.tar.gz
# command to install dependencies
install: "pip install -q -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
