language: python
cache: pip

#dist: precise
sudo: false

env:
  global:
    - ABINIT_VERSION=8.8.2
    - ABIPY_PYTEST=yes
    - OPENBLAS_NUM_THREADS=1
    - OMP_NUM_THREADS=1
  - secure: l+S0aIlco/q33mJhkX76/WykVvALOIPSBIq8smQUUXbGj7kBCjNLCj8P26WnjB5FwUFKjh5svlCrT0oqdiiSimVUuUKdozB8zKa0fyMa8G1//WKSwwsfVlQlcDxWEh9pT7Ox39Jau1ODz31tYvVwdCgEQohk/0uc92uLp4/Q9gSfLdtyW1qGx+2fFBO/Slfb6makdYsRk+QQmHwC+lqnghhzP4dIbWmSy1+EDGcSQN9UFWPEcYi3Thh9TAkZ1iQEEDQptebddESYPPHlgvWfk1hGaBG481jI/Ydmz6FFbXkLCY/bLZ/cntzPEImZFJVGEbK5nfWJpd6es9KcslMPDW5sDWbd6pL4W/mkUGdAqq/Mi/hr/yECmBLmbt13BzyPDqbfwkv/kRGqIKOHVv6RtpgaIoZXe/OR/M9kY+lI6/Oye7MgknRqzYqt6Nh6bXno3LyvDHwfApN9aUqUx6LFAmpZ2/Ki6CAvl54oXR9CPNQPzDQ5Rprjia4GJogPHQ2MsceNbIimZJXSqN9vLnhB5aYF5Oh+9out1Uv9n2D42vadguCvvjUJJWLMfqFtLDT9rme1Ye1cHtajDvDpXS1ddfvts5bum17nLUiE+mfViJBjwvJwSEGJoeQzfln4i4jQo3VQFoZDDRPJKT3cooeNdhtB09gfF0SbcB16A2DCquk=

matrix:
  include:
    - os: linux
      python: 2.7
      env: 
        - ABIPY_INSTALLER=conda
    - os: linux
      python: 3.6
      env: 
        - ABIPY_INSTALLER=conda ABIPY_COVERALLS=yes
    - os: linux
      python: 3.6
      env: 
        - ABIPY_INSTALLER=pip ABIPY_SPHINX=yes ABIPY_PYTEST=no
    #- os: osx
    #  python: 3.6
    #  language: generic
    #  env: 
    #    - ABIPY_INSTALLER=conda ABIPY_PYTEST=no
    - os: linux
      python: 3.7
      # https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
      env: 
        - ABIPY_INSTALLER=pip

install:
  #- set -ev  # exit on first error, print each command
  - env
  #- ulimit -s unlimited

  - |
      if [ "${ABIPY_INSTALLER}" == "pip" ]; then
        # pip-based installation.
        source dev_scripts/conda_get.sh  # Needed for Abinit
        echo "Installing abinit from abinit channel ..."
        conda config --add channels conda-forge
        conda install -y -c abinit abinit=${ABINIT_VERSION}
        abinit --version
        abinit --build

        sed -i '/pymatgen/d' requirements.txt
        travis_wait pip install -r requirements.txt
        travis_wait pip install -r requirements-optional.txt
        #travis_wait pip uninstall -y pymatgen

      elif [ "${ABIPY_INSTALLER}" == "conda" ]; then
        # Install conda https://conda.io/docs/travis.html
        source dev_scripts/conda_get.sh
        #sed -i '/pymatgen/d' requirements.txt
        source dev_scripts/conda_install.sh
        conda uninstall -y pymatgen
      fi

  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then conda install mock; fi
  #- pip install graphviz

  # Mayavi (optional requirement)
  #- if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then conda install mayavi; fi
  #- if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]; then conda install vtk && pip install mayavi; fi

  # Use gmatteo's pymatgen fork
  #- git clone --depth=50 https://github.com/gmatteo/pymatgen.git && cd pymatgen && pip install -r requirements.txt && pip install -r requirements-optional.txt && python setup.py install && cd ../

  - git clone --depth=50 https://github.com/gmatteo/pymatgen.git && cd pymatgen && python setup.py install && cd ../

  # Use pymatgen master
  #- git clone --depth=50 https://github.com/materialsproject/pymatgen.git && cd pymatgen && pip install -r requirements.txt && pip install -r requirements-optional.txt && python setup.py install && cd ../

  - python setup.py install
  - mkdir -p ${HOME}/.abinit/abipy 
  - cp abipy/data/managers/travis_scheduler.yml ${HOME}/.abinit/abipy/scheduler.yml
  - cp abipy/data/managers/travis_manager.yml ${HOME}/.abinit/abipy/manager.yml
  - ./dev_scripts/pyclean.py .

before_script:
    # This to run tests requiring a graphical user e.g. mayavi
    # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    # https://github.com/travis-ci/travis-ci/issues/6307
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then rvm get head || true; fi 

# command to run tests
script: ./dev_scripts/runtests.sh

branches:
  only:
    - master
    - develop
    - gp_qha

after_success:
    - if [[ "${ABIPY_COVERALLS}" == "yes" ]]; then coveralls; fi

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always

# https://docs.travis-ci.com/user/deployment/pages/
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: ${TRAVIS_BUILD_DIR}/yourfolder
#  on:
#    branch: master
