#name: env2.7
channels:
- abinit
- matsci
- conda-forge
- defaults
dependencies:
- apscheduler=2.1.0=py27_0
- html2text=2016.9.19=py27_0
- alabaster=0.7.10=py27_0
#- appnope=0.1.0=py27_0 # This is MacOsX specific, should create 2 envs
- apptools=4.4.0=py27_0
- ase=3.13.0=py27_1
- babel=2.3.4=py27_0
- backports=1.0=py27_1
- backports.functools_lru_cache=1.4=py27_1
- backports.shutil_get_terminal_size=1.0.0=py27_1
- backports_abc=0.5=py27_0
- bkcharts=0.2=py27_0
- blas=1.1=openblas
- bleach=1.5.0=py27_0
- bokeh=0.12.6=py27_0
- ca-certificates=2017.1.23=0
- certifi=2017.1.23=py27_0
- click=6.7=py27_0
- cloudpickle=0.3.1=py27_0
- configparser=3.5.0=py27_0
- coverage=4.3.4=py27_0
- curl=7.52.1=0
- cycler=0.10.0=py27_0
- dask=0.15.0=py27_0
- dask-core=0.16.0=py_0
- decorator=4.0.11=py27_0
- distributed=1.17.1=py27_0
- docutils=0.13.1=py27_0
- entrypoints=0.2.2=py27_1
- enum34=1.1.6=py27_1
- envisage=4.5.1=py27_0
- fastcache=1.0.2=py27_0
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_1
- futures=3.0.5=py27_0
- gmp=6.1.2=0
- gmpy2=2.0.8=py27_1
- hdf4=4.2.12=0
- hdf5=1.10.1=1
- heapdict=1.0.0=py27_0
- html5lib=0.999=py27_0
- icu=58.1=1
- imageio=2.2.0=py27_0
- imagesize=0.7.1=py27_0
- ipykernel=4.5.2=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- jinja2=2.9.5=py27_0
- jpeg=9b=0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=5.0.0=py27_0
- jupyter_console=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- jupyterlab=0.27.0=py27_1
- jupyterlab_launcher=0.4.1=py27_0
- libgfortran=3.0.0=0
- libiconv=1.15=0
- libnetcdf=4.5.0=3
- libpng=1.6.34=0
- libsodium=1.0.10=0
- libtiff=4.0.9=0
- libxml2=2.9.5=2
- locket=0.2.0=py27_1
- markupsafe=0.23=py27_1
- matplotlib=2.1.1=py27_2
- mistune=0.7.4=py27_0
- mock=2.0.0=py27_0
- mpc=1.0.3=4
- mpfr=3.1.5=0
- mpmath=1.0.0=py_0
- msgpack-python=0.4.8=py27_0
- nbconvert=5.1.1=py27_1
- nbformat=4.2.0=py27_0
- ncurses=5.9=10
- netcdf4=1.3.1=py27_2
- networkx=1.11=py27_0
- nose=1.3.7=py27_2
- notebook=5.0.0=py27_0
- numpy=1.13.3=py27_blas_openblas_201
- olefile=0.44=py27_0
- openblas=0.2.20=6
- openssl=1.0.2h=3
- palettable=3.1.0=py_0
- pandas=0.21.1=py27_0
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py27_0
- partd=0.3.8=py27_0
- pathlib2=2.2.1=py27_0
- patsy=0.4.1=py27_0
- pbr=2.0.0=py27_0
- pexpect=4.2.1=py27_0
- phonopy=1.12.2.20=py27_0
- pickleshare=0.7.3=py27_0
- pillow=4.3.0=py27_2
- pip=9.0.1=py27_0
- plotly=2.0.12=py27_0
- prettytable=0.7.2=py27_1
- prompt_toolkit=1.0.14=py27_0
- psutil=5.2.1=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.4.33=py27_0
- pydispatcher=2.0.5=py27_0
- pyface=5.1.0=py27_1
- pygments=2.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=4.11.4=py27_2
- pytest=3.0.7=py27_0
- pytest-cov=2.4.0=py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- pywavelets=0.5.2=py27_1
- pyyaml=3.12=py27_1
- pyzmq=16.0.2=py27_1
- qtconsole=4.3.0=py27_0
- readline=6.2=0
- requests=2.13.0=py27_0
- ruamel.ordereddict=0.4.13=py27_0
- ruamel.yaml=0.15.35=py27_0
- scandir=1.5=py27_1
- scikit-image=0.13.0=py27_3
- scipy=1.0.0=py27_blas_openblas_201
- seaborn=0.8.1=py27_0
- setuptools=33.1.1=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.11.0=py27_1
- snowballstemmer=1.2.1=py27_0
- sortedcontainers=1.5.3=py27_0
- spglib=1.10.2.4=py27_0
- sphinx=1.5.3=py27_0
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_1
- statsmodels=0.8.0=py27_0
- subprocess32=3.2.7=py27_0
- sympy=1.1.1=py27_0
- tabulate=0.8.1=py_0
- tblib=1.3.2=py27_0
- terminado=0.6=py27_0
- testpath=0.3=py27_0
- tk=8.5.19=1
- toolz=0.8.2=py27_0
- tornado=4.4.2=py27_0
- tqdm=4.19.5=py_0
- traitlets=4.3.2=py27_0
- traits=4.6.0=py27_1
- traitsui=5.1.0=py27_0
- typing=3.6.2=py27_0
- vispy=0.5.2=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=2.0.0=py27_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zict=0.1.2=py27_0
- zlib=1.2.11=0
- configobj=5.0.6=py27_0
- llvmlite=0.20.0=py27_0
- mayavi=4.5.0=py27_0
- mkl=2017.0.1=0
- numba=0.35.0=np113py27_0
- python.app=1.2=py27_4
- qgrid=0.3.3=py27_0
- qt=4.8.7=4
- vtk=6.3.0=py27_1
- wxpython=3.0=py27_0
- monty=1.0.0=py27hcd6e15c_2
- pymatgen=2017.9.23=py27hd54e414_0
- pip:
  - appdirs==1.4.3
  - atomicfile==1.0
  - backports-abc==0.5
  - backports.functools-lru-cache==1.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - betterbib==2.4.1
  - chardet==3.0.4
  - gooey==0.9.2.3
  - greenlet==0.4.12
  - idna==2.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - jupyterlab-launcher==0.4.1
  - latexcodec==1.0.5
  - linkchecker==9.3
  - livereload==2.5.1
  - markdown==2.6.8
  - markdown-newtab==0.2.0
  - mkdocs==0.16.3
  - monty==1.0.0
  - pipdate==0.2.1
  - plastex==1.0
  - prompt-toolkit==1.0.14
  - pybtex==0.21
  - pylinkvalidator==0.3
  - pymatgen==2017.9.23
  - pymdown-extensions==3.5
  - pypandoc==1.4
  - python-markdown-math==0.3
  - ranger==0.10
  - scripttest==1.3
  - trollius==2.1
  - urllib3==1.21.1
  - wxpython-common==3.0.0.0
#prefix: /Users/gmatteo/anaconda3/envs/env2.7

