#name: env3.6
channels:
- clinicalgraphics
- abinit
- matsci
- conda-forge
- defaults
dependencies:
- vtk=7.1.0=py36_3
#- appnope=0.1.0=py36_0  # This is MacOsX specific, should create 2 envs
- argh=0.26.2=py36_1
- ase=3.13.0=py36_1
- babel=2.3.4=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- blas=1.1=openblas
- bleach=1.5.0=py36_0
- bokeh=0.12.9=py36_0
- boto3=1.4.4=py36_0
- botocore=1.5.39=py36_0
- bottleneck=1.2.0=np112py36_0
- ca-certificates=2017.1.23=0
- certifi=2017.1.23=py36_0
- click=6.7=py36_0
- cloudpickle=0.2.2=py36_2
- coverage=4.0.3=py36_1
- curl=7.52.1=0
- cycler=0.10.0=py36_0
- dask=0.14.1=py36_0
- decorator=4.0.11=py36_0
- distributed=1.16.1=py36_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.2=py36_1
- flask=0.12.2=py36_0
- freetype=2.7=1
- gmp=6.1.2=0
- greenlet=0.4.12=py36_0
- h5netcdf=0.3.1=py36_0
- h5py=2.7.0=np112py36_0
- hdf4=4.2.12=0
- hdf5=1.8.17=9
- heapdict=1.0.0=py36_0
- html5lib=0.999=py36_0
- icu=58.1=1
- imageio=2.2.0=py36_0
- imagesize=0.7.1=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- itsdangerous=0.24=py_2
- jedi=0.10.2=py36_0
- jinja2=2.9.5=py36_0
- jmespath=0.9.2=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.0.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- jupyter_dashboards=0.7.0=py36_0
- jupyterlab=0.29.1=py36_0
- jupyterlab_launcher=0.5.5=py36_0
- latexcodec=1.0.4=py36_0
- libgfortran=3.0.0=0
- libnetcdf=4.4.1.1=2
- libpng=1.6.28=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- livereload=2.5.1=py36_0
- locket=0.2.0=py36_1
- markupsafe=0.23=py36_1
- matplotlib=2.1.0=py36_1
- mistune=0.7.4=py36_0
- mkdocs=0.16.3=py36_0
- mkdocs-bootstrap=0.1.1=py36_0
- mkdocs-bootswatch=0.4.0=py36_0
- mongoengine=0.11.0=py36_0
- mpc=1.0.3=3
- mpfr=3.1.5=0
- mpich=3.2=4
- msgpack-python=0.4.8=py36_0
- nb_conda=2.2.1=py36_0
- nb_conda_kernels=2.1.0=py36_0
- nbconvert=5.2.1=py36_1
- nbformat=4.2.0=py36_0
- ncurses=5.9=10
- neovim=0.2.0=py36_0
- netcdf-fortran=4.4.4=2
- netcdf4=1.2.7=np112py36_0
- networkx=1.11=py36_0
- nose=1.3.7=py36_2
- notebook=5.1.0=py36_0
- numpy=1.12.1=py36_blas_openblas_201
- olefile=0.44=py36_0
- openblas=0.2.20=6
- openssl=1.0.2h=3
- pandas=0.19.2=np112py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- partd=0.3.7=py36_0
- pathtools=0.1.2=py36_0
- patsy=0.4.1=py36_0
- pep8=1.7.0=py36_0
- pexpect=4.2.1=py36_0
- phonopy=1.11.8=np112py36_2
- pickleshare=0.7.3=py36_0
- pillow=4.2.0=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.14=py36_0
- psutil=5.2.1=py36_0
- ptyprocess=0.5.1=py36_0
- py=1.4.33=py36_0
- pygments=2.2.0=py36_0
- pyopengl=3.1.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=4.11.4=py36_2
- pytest=3.0.7=py36_0
- python=3.6.1=0
- python-coveralls=2.9.0=py36_0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pywavelets=0.5.2=np112py36_0
- pyyaml=3.12=py36_1
- pyzmq=16.0.2=py36_1
- qt=4.8.7=7
- qtconsole=4.3.0=py36_0
- readline=6.2=0
- requests=2.13.0=py36_0
- ruamel.yaml=0.15.6=py36_0
- s3fs=0.0.9=py36_0
- s3transfer=0.1.10=py36_1
- scikit-image=0.13.0=np112py36_0
- scipy=1.0.0=py36_blas_openblas_201
- seaborn=0.7.1=py36_0
- setuptools=33.1.1=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- snowballstemmer=1.2.1=py36_0
- sortedcontainers=1.5.3=py36_0
- sphinx=1.6.5=py36_0
- sphinxcontrib-websupport=1.0.1=py36_0
- sqlite=3.13.0=1
- tblib=1.3.2=py36_0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.19=1
- toolz=0.8.2=py36_0
- tornado=4.4.2=py36_0
- traitlets=4.3.2=py36_0
- typing=3.6.2=py36_0
- visvis=1.10.0=py36_2
- watchdog=0.8.3=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- werkzeug=0.12.2=py_1
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- wtforms=2.1=py36_0
- xarray=0.9.5=py36_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zict=0.1.1=py36_0
- zlib=1.2.11=0
- alabaster=0.7.10=py36_0
- cloog=0.18.0=0
- gcc=4.8.5=8
- isl=0.12.2=1
- markdown=2.6.8=py36_0
- mkl=2017.0.1=0
- pymongo=3.3.0=py36_0
- qgrid=0.3.3=py36_0
- statsmodels=0.8.0=np112py36_0
- pybtex=0.20.1=py36_0
- pip:
  - apipkg==1.4
  - appdirs==1.4.3
  - apptools==4.4.0
  - apscheduler==2.1.0
  - asn1crypto==0.24.0
  - atomicfile==1.0
  - autodoc==0.3
  - backports.functools-lru-cache==1.4
  - beautifulsoup4==4.6.0
  - betterbib==3.1.3
  - cdiff==1.0
  - cffi==1.11.2
  - chardet==3.0.4
  - chemview==0.6
  - commonmark==0.7.4
  - configobj==5.0.6
  - cryptography==2.1.4
  - custodian==1.1.0
  - doc8==0.8.0
  - envisage==4.6.0
  - execnet==1.5.0
  - fireworks==1.4.2
  - flask-mongoengine==0.9.2
  - flask-paginate==0.5.1
  - flask-wtf==0.14.2
  - future==0.16.0
  - ghp-import==0.5.5
  - gunicorn==19.7.1
  - html2text==2016.9.19
  - idna==2.6
  - invoke==0.22.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - jupyter-dashboards==0.7.0
  - jupyter-pip==0.3
  - jupyterlab-launcher==0.5.5
  - jupyterthemes==0.18.2
  - lesscpy==0.12.0
  - linkchecker==9.4
  - markdown-newtab==0.2.0
  - markups==2.0.1
  - mayavi==4.5.0
  - mkdocs-cinder==0.9.4
  - mkdocs-material==1.10.1
  - mkdocs-windmill==0.1.2
  - mock==2.0.0
  - monty==1.0.1
  - moviepy==0.2.3.2
  - mpmath==0.19
  - nb-conda==2.2.1
  - nb-conda-kernels==2.1.0
  - nbjsmol==0.0.0
  - nbsphinx==0.2.16
  - oset==0.1.3
  - palettable==3.0.0
  - paramiko==2.1.2
  - parso==0.1.0
  - pbr==3.1.1
  - periodic-table-plotter==0.2
  - phononwebsite==0.1
  - pipdate==0.2.1
  - plastex==1.0
  - plotly==2.0.12
  - ply==3.10
  - pockets==0.3.2
  - port-for==0.3.1
  - prettytable==0.7.2
  - prompt-toolkit==1.0.15
  - py-w3c==0.3.1
  - pyasn1==0.4.2
  - pybtex-docutils==0.2.1
  - pycparser==2.18
  - pydispatcher==2.0.5
  - pyenchant==2.0.0
  - pyface==5.1.0
  - pymatgen==2017.12.16
  - pymdown-extensions==4.0
  - pypandoc==1.4
  - pyqt5==5.9
  - pytest-cov==2.4.0
  - pytest-forked==0.2
  - pytest-xdist==1.20.1
  - python-igraph==0.7.1.post6
  - python-markdown-math==0.3
  - pytidylib==0.3.2
  - releases==1.4.0
  - restructuredtext-lint==1.1.1
  - retext==7.0.1
  - ruamel.std.argparse==0.7.1
  - ruamel.yaml.cmd==0.2.4
  - scripttest==1.3
  - semantic-version==2.6.0
  - spglib==1.9.9.44
  - sphinx-argparse==0.2.1
  - sphinx-autobuild==0.7.1
  - sphinx-bootstrap-theme==0.6.0
  - sphinx-gallery==0.1.13
  - sphinxcontrib-argdoc==0.1.3
  - sphinxcontrib-autoprogram==0.1.3
  - sphinxcontrib-bibtex==0.3.6
  - sphinxcontrib-napoleon==0.6.1
  - sphinxcontrib-programoutput==0.10
  - stevedore==1.27.1
  - sympy==1.0
  - tabulate==0.7.7
  - tqdm==4.19.5
  - traits==4.6.0
  - traitsui==5.1.0
  - urllib3==1.22
  - vapory==0.1.1
  - waitress==1.1.0
  - webob==1.7.3
  - webtest==2.0.29
#prefix: /Users/gmatteo/anaconda3/envs/env3.6

